# Generated by Django 2.1.4 on 2018-12-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181206_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='igp',
            old_name='org_rep',
            new_name='org',
        ),
    ]
