# Generated by Django 2.1.7 on 2019-02-20 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
        ('app', '0010_auto_20190220_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL),
            preserve_default=False,
        ),
    ]
