# Generated by Django 2.1.7 on 2019-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190221_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igp',
            name='rating',
        ),
        migrations.AddField(
            model_name='igp',
            name='qwe',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
