# Generated by Django 2.1.7 on 2019-02-21 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
        ('app', '0013_auto_20190221_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igp',
            name='qwe',
        ),
        migrations.AddField(
            model_name='igp',
            name='rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL),
        ),
    ]
